version: 2
jobs:
  "build-1404":
    working_directory: ~/isl
    resource_class: xlarge
    docker:
      - image: nicolasvasilache/tc-1404-llvm4.0-src:latest

    steps:
      - checkout

      - run:
          name: build-isl
          command: |
            cd ~/isl
            export ISL_DIR=$(pwd)
            VERBOSE=1 TRAVIS=1 CORES=16 CMAKE_VERSION="cmake" CLANG_PREFIX="$(/clang+llvm-4.0/bin/llvm-config --prefix)" ./build.sh --isl

      - run:
          name: test_isl
          command: |
            cd ~/isl
            ./flags.sh ./build/isl_test
            ./flags.sh ./build/isl_test_int

  "build-1604":
    working_directory: ~/isl
    resource_class: xlarge
    docker:
      - image: nicolasvasilache/tc-1604-llvm4.0-src:latest

    steps:
      - checkout

      - run:
          name: build-isl
          command: |
            cd ~/isl
            export ISL_DIR=$(pwd)
            VERBOSE=1 TRAVIS=1 CORES=16 CMAKE_VERSION="cmake" CLANG_PREFIX="$(/clang+llvm-4.0/bin/llvm-config --prefix)" ./build.sh --isl

      - run:
          name: test_isl
          command: |
            cd ~/isl
            ./flags.sh ./build/isl_test
            ./flags.sh ./build/isl_test_int
workflows:
  version: 2
  build:
    jobs:
      - "build-1404"
      - "build-1604"
